/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: dd312ff2f1b6977039db6737923d7045)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	APP_ORIGIN: string;
	CLERK_JWT_KEY: string;
	CLERK_ISSUER: string;
	CLERK_FRONTEND_ORIGIN: string;
	CREEM_PRODUCT_ID: string;
	CREEM_ENVIRONMENT: string;
	BILLING_ACQUISITION_ENABLED: string;
	CREEM_API_KEY: string;
	CREEM_WEBHOOK_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "CLERK_JWT_KEY" | "CLERK_ISSUER" | "CLERK_FRONTEND_ORIGIN" | "CREEM_PRODUCT_ID" | "CREEM_ENVIRONMENT" | "BILLING_ACQUISITION_ENABLED" | "CREEM_API_KEY" | "CREEM_WEBHOOK_SECRET">> {}
}
