import { expect, test } from '@playwright/test'
import { NETWORKS } from '../src/data'

for (const locale of ['ko', 'en'] as const) {
  const ko = locale === 'ko'
  test(`${locale}: reset removes view state and search while preserving unrelated parameters`, async ({ page }) => {
    await page.goto(`/${locale}/map?network=securities-issuance&mode=map&issuance=us-equity-ipo&compareIssuance=adr-depository-issuance&ref=lesson`)
    const search = page.getByLabel(ko ? '금융 네트워크 검색' : 'Search financial networks')
    await search.fill('SWIFT')
    await page.getByRole('button', { name: ko ? '선택 초기화' : 'Reset selection', exact: true }).click()
    await expect(page).toHaveURL(`/${locale}/map?ref=lesson`)
    await expect(search).toHaveValue('')
    await expect(page.locator('.network-list button')).toHaveCount(NETWORKS.length)
    await expect(page.locator('.source-data-heading h2')).toHaveText('CHIPS · Fedwire')
    await page.getByLabel(ko ? '네트워크' : 'Network', { exact: true }).selectOption('securities-issuance')
    await expect(page.locator('.issuance-selected-card h4')).toHaveText(ko ? '기관 모기지증권 발행' : 'Agency mortgage-backed securities issuance')
    await expect(page.locator('.issuance-comparison-grid')).toHaveCount(0)
    await expect(page.getByRole('searchbox', { name: ko ? '절차 검색' : 'Search procedures' })).toHaveValue('')
    await expect(page.getByLabel(ko ? '분류' : 'Category', { exact: true })).toHaveValue('all')
    await page.reload()
    await expect(page.locator('.issuance-selected-card h4')).toHaveText(ko ? '기관 모기지증권 발행' : 'Agency mortgage-backed securities issuance')
  })

  test(`${locale}: network search preserves selection, clears and restores shared selection`, async ({ page }) => {
    await page.goto(`/${locale}/map?network=swift`)
    const search = page.getByLabel(ko ? '금융 네트워크 검색' : 'Search financial networks')
    await search.fill('not-a-network')
    await expect(page.locator('.network-list button')).toHaveCount(0)
    await expect(page.locator('.network-sidebar .selection-filter-notice')).toContainText('SWIFT')
    await expect(page.locator('.source-data-heading h2')).toHaveText('SWIFT')
    await expect(page).toHaveURL(/network=swift$/)
    await page.locator('.network-sidebar .selection-filter-notice button').click()
    await expect(search).toHaveValue('')
    await expect(search).toBeFocused()
    await search.fill(ko ? '담보관리' : 'Tri-party')
    await page.locator('.network-list button').filter({ hasText: 'Tri-party' }).click()
    const sharedUrl = page.url()
    await page.goto(sharedUrl)
    await expect(page.locator('.source-data-heading h2')).toContainText('Tri-party')
    await expect(search).toHaveValue('')
  })

  test(`${locale}: issuance selection survives filtering, empty results and comparison`, async ({ page }) => {
    await page.goto(`/${locale}/map?network=securities-issuance&issuance=us-equity-ipo`)
    const originalUrl = page.url()
    const title = await page.locator('.issuance-selected-card h4').innerText()
    const search = page.getByRole('searchbox', { name: ko ? '절차 검색' : 'Search procedures' })
    await page.getByLabel(ko ? '분류' : 'Category', { exact: true }).selectOption('treasury')
    const notice = page.locator('#issuance-library .selection-filter-notice')
    await expect(notice).toBeVisible()
    await expect(page.locator('.issuance-results > li')).toHaveCount(9)
    await search.fill('no-such-procedure')
    await expect(page.locator('.issuance-empty')).toBeVisible()
    await expect(notice).toBeVisible()
    await expect(page.locator('.issuance-selected-card h4')).toHaveText(title)
    await expect(page).toHaveURL(originalUrl)
    await page.getByRole('button', { name: ko ? '경로 비교' : 'Compare', exact: true }).click()
    await expect(notice).toHaveCount(0)
    await page.getByRole('button', { name: ko ? '비교 닫기' : 'Close compare' }).click()
    await expect(notice).toBeVisible()
    await notice.getByRole('button').focus()
    await page.keyboard.press('Enter')
    await expect(search).toBeFocused()
    await expect(search).toHaveValue('')
    await expect(page.locator('.issuance-results > li')).toHaveCount(29)
    await expect(page.locator('.issuance-results button[aria-pressed="true"]')).toContainText(title)
    await expect(page).toHaveURL(originalUrl)
    await search.fill('bills')
    await page.getByRole('button', { name: ko ? '필터 초기화' : 'Reset filters', exact: true }).focus()
    await page.keyboard.press('Enter')
    await expect(search).toBeFocused()
    await expect(search).toHaveValue('')
    await search.fill('bills')
    await page.locator('.issuance-search button').focus()
    await page.keyboard.press('Enter')
    await expect(search).toBeFocused()
    await expect(search).toHaveValue('')
  })
}

test('320px search controls fit the viewport and retain touch targets', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 844 })
  await page.goto('/en/map')
  const search = page.getByLabel('Search financial networks')
  await search.fill('SWIFT')
  const input = await search.boundingBox()
  const clear = await page.getByLabel('Clear network search').boundingBox()
  expect(input!.height).toBeGreaterThanOrEqual(44)
  expect(clear!.width).toBeGreaterThanOrEqual(44)
  expect(clear!.height).toBeGreaterThanOrEqual(44)
  expect(clear!.x + clear!.width).toBeLessThanOrEqual(320)
  expect(await search.evaluate(el => getComputedStyle(el).fontSize)).toBe('16px')
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)
  await page.getByLabel('Clear network search').click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)
})

test('desktop network arrow navigation keeps focus and selection together', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'Desktop keyboard navigation')
  await page.goto('/en/map')
  const buttons = page.locator('.network-list button')
  await buttons.first().focus()
  await page.keyboard.press('ArrowDown')
  await expect(buttons.nth(1)).toBeFocused()
  await expect(buttons.nth(1)).toHaveAttribute('aria-pressed', 'true')
  await page.keyboard.press('Home')
  await expect(buttons.first()).toBeFocused()
  await expect(buttons.first()).toHaveAttribute('aria-pressed', 'true')
})
