import { test, expect } from '@playwright/test'

for (const locale of ['ko', 'en'] as const) {
  const ko = locale === 'ko'
  test(`${locale}: glossary searches across languages, explains distinctions and opens a related flow`, async ({ page }) => {
    await page.goto(`/${locale}/learn`)
    const glossary = page.getByRole('region', { name: ko ? '헷갈리는 금융 용어, 여기서 찾아보세요' : 'Make sense of unfamiliar finance terms' })
    const search = glossary.getByRole('searchbox', { name: ko ? '금융 용어 검색' : 'Search finance terms' })
    await expect(glossary.getByRole('article')).toHaveCount(9)
    await search.fill('RTGS')
    await expect(glossary.getByRole('article')).toHaveCount(1)
    await expect(glossary.getByRole('heading', { level: 3 })).toHaveText(ko ? '실시간 총액결제' : 'Real-time gross settlement')
    await expect(glossary).toContainText(ko ? '여러 지급을 상계한 차액을 나중에 결제하는 방식과 구분합니다.' : 'This differs from settling netted payment batches later.')
    await expect(glossary.getByRole('link', { name: /Reserve Bank of Australia/ })).toHaveAttribute('href', /rba.gov.au/)
    await expect(glossary).toContainText('2026-09-23')
    await search.fill('해외 송금')
    await expect(glossary.getByRole('heading', { level: 3 })).toHaveText(ko ? '지급 메시지' : 'Payment message')
    await search.fill('not-a-financial-term')
    await expect(glossary.getByRole('article')).toHaveCount(0)
    await expect(glossary).toContainText(ko ? '일치하는 용어가 없습니다.' : 'No matching terms.')
    await glossary.getByRole('button', { name: ko ? '모든 용어 보기' : 'Show all terms' }).click()
    await expect(search).toBeFocused()
    await expect(search).toHaveValue('')
    await expect(glossary.getByRole('article')).toHaveCount(9)
    await search.fill('bank transfer')
    await glossary.getByRole('button', { name: ko ? 'SWIFT 흐름 보기' : 'Explore SWIFT', exact: true }).click()
    await expect(page).toHaveURL(new RegExp(`/${locale}/map\\?network=swift$`))
    await expect(page.getByRole('heading', { name: ko ? '흐름 이해하기' : 'Understand the flow', exact: true })).toBeVisible()
  })
}

test('term links survive reload and language switching without replacing the existing learning routes', async ({ page }) => {
  await page.goto('/en/learn?term=netting')
  const netting = page.getByRole('article', { name: 'Netting', exact: true })
  await expect(netting).toBeFocused()
  await expect(netting).toContainText('Calculating a net amount does not mean the remaining payment is complete.')
  await page.reload()
  await expect(netting).toBeFocused()
  await page.getByRole('button', { name: '한국어로 전환' }).click()
  await expect(page).toHaveURL(/\/ko\/learn\?term=netting$/)
  await expect(page.getByRole('article', { name: '상계', exact: true })).toBeVisible()
  await page.getByRole('button', { name: /메시지와 돈/ }).click()
  await expect(page).toHaveURL(/\/ko\/learn\/1$/)
  await expect(page.getByRole('region', { name: '메시지와 돈 · 상세 가이드', exact: true })).toBeFocused()
})

test('a valid term link takes precedence over conflicting search and preserves unrelated URL state', async ({ page }) => {
  await page.goto('/en/learn?term=netting&q=RTGS&from=guide')
  await expect(page).toHaveURL(/\/en\/learn\?term=netting&from=guide$/)
  await expect(page.getByRole('article', { name: 'Netting', exact: true })).toBeFocused()
  const search = page.getByRole('searchbox', { name: 'Search finance terms' })
  await expect(search).toHaveValue('')
  await search.fill('RTGS')
  await expect(page).toHaveURL(/\/en\/learn\?from=guide&q=RTGS$/)
  await expect(page.getByRole('region', { name: 'Make sense of unfamiliar finance terms' }).getByRole('article')).toHaveCount(1)
  await expect(page.getByRole('article', { name: 'Real-time gross settlement', exact: true })).toBeVisible()
})

test('glossary direct links, unknown terms and controls remain usable at 320px', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 800 })
  await page.goto('/en/learn?term=unknown')
  const glossary = page.getByRole('region', { name: 'Make sense of unfamiliar finance terms' })
  await expect(glossary.getByRole('status')).toContainText('The linked term was not found.')
  await glossary.getByRole('button', { name: 'Clear search', exact: true }).click()
  await expect(page).toHaveURL(/\/en\/learn$/)
  const authorization = glossary.getByRole('article', { name: 'Card authorization', exact: true })
  await authorization.getByRole('link', { name: 'Direct link to Card authorization', exact: true }).click()
  await expect(page).toHaveURL(/\/en\/learn\?term=authorization$/)
  await expect(authorization).toBeFocused()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const search = glossary.getByRole('searchbox', { name: 'Search finance terms' })
  await search.fill('zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await search.press('Escape')
  await expect(search).toHaveValue('')
  await expect(search).toBeFocused()
})
