import { expect, test } from '@playwright/test'

test('browser copies survive reload, protect current edits, search and export without an account', async ({ page }) => {
  await page.goto('/en/workspace')
  const notebook = page.getByRole('region', { name: /^Browser notebook/ })
  const save = notebook.getByRole('button', { name: 'Keep a copy of this draft' })
  await page.getByLabel('Brief title').fill('First research')
  await page.getByLabel('Your perspective and questions').fill('An important question about messaging')
  await save.click()
  await save.click()
  await expect(notebook.getByText('This exact draft is already in your notebook. No duplicate was added.')).toBeVisible()
  await expect(notebook.getByRole('button', { name: /^Open saved draft/ })).toHaveCount(1)
  await page.getByLabel('Brief title').fill('Second research')
  await page.getByLabel('Your perspective and questions').fill('Different work that must stay')
  await save.click()
  await page.reload()
  await expect(notebook.getByRole('button', { name: /^Open saved draft/ })).toHaveCount(2)
  await notebook.getByRole('searchbox', { name: 'Search browser notebook' }).fill('messaging')
  await expect(notebook.getByRole('button', { name: /^Open saved draft/ })).toHaveCount(1)
  await notebook.getByRole('button', { name: 'Open saved draft First research' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByLabel('Brief title')).toHaveValue('Second research')
  await notebook.getByRole('button', { name: 'Open saved draft First research' }).click()
  await page.getByRole('button', { name: 'Replace draft', exact: true }).click()
  await expect(page.getByLabel('Brief title')).toHaveValue('First research')
  await page.getByRole('button', { name: 'Undo draft replacement' }).click()
  await expect(page.getByLabel('Your perspective and questions')).toHaveValue('Different work that must stay')

  const downloaded = page.waitForEvent('download')
  await notebook.getByRole('button', { name: 'Back up saved draft First research' }).click()
  const file = await downloaded
  const stream = await file.createReadStream()
  let content = ''
  for await (const chunk of stream!) content += chunk.toString()
  const backup = JSON.parse(content)
  expect(backup).toMatchObject({ format: 'flow-of-money-brief', draft: { title: 'First research', notes: 'An important question about messaging' } })
  expect(Object.keys(backup.draft).sort()).toEqual(['locale', 'networks', 'notes', 'title'])

  await notebook.getByRole('searchbox').fill('no result')
  await expect(notebook.getByText('No matching copies.')).toBeVisible()
  await notebook.getByRole('button', { name: 'Clear notebook search' }).click()
  await notebook.getByLabel('Sort browser notebook').selectOption('title')
  await expect(notebook.locator('.brief-open strong')).toHaveText(['First research', 'Second research'])
  page.once('dialog', dialog => dialog.dismiss())
  await notebook.getByRole('button', { name: 'Delete saved draft First research' }).click()
  await expect(notebook.getByRole('button', { name: /^Open saved draft/ })).toHaveCount(2)
  page.once('dialog', dialog => dialog.accept())
  await notebook.getByRole('button', { name: 'Delete saved draft First research' }).click()
  await expect(notebook.getByRole('button', { name: /^Open saved draft/ })).toHaveCount(1)
  await expect(page.getByLabel('Brief title')).toHaveValue('Second research')
})

test('unfinished drafts can be kept and reopened using the current source snapshot', async ({ page }) => {
  await page.goto('/en/workspace')
  const notebook = page.getByRole('region', { name: /^Browser notebook/ })
  await page.getByLabel('Brief title').fill('')
  await page.getByRole('checkbox', { name: 'SWIFT', exact: true }).uncheck()
  await page.getByRole('checkbox', { name: 'CHIPS · Fedwire', exact: true }).uncheck()
  await page.getByLabel('Your perspective and questions').fill('An unfinished thought')
  await notebook.getByRole('button', { name: 'Keep a copy of this draft' }).click()
  await page.getByRole('button', { name: 'New draft', exact: true }).click()
  await page.getByRole('button', { name: 'Replace draft', exact: true }).click()
  await notebook.getByRole('button', { name: 'Open saved draft Untitled draft' }).click()
  await expect(page.getByLabel('Brief title')).toHaveValue('')
  await expect(page.getByLabel('Your perspective and questions')).toHaveValue('An unfinished thought')
  await expect(page.getByRole('checkbox', { checked: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Export Markdown', exact: true })).toBeDisabled()
  await expect(notebook).toContainText('Reopening uses current sources for the preview.')
})

test('corrupt records and failed storage writes preserve the draft and existing records', async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem('fin-flow:local-brief:v1:broken', '{broken')
    const setItem = Storage.prototype.setItem
    Storage.prototype.setItem = function (key, value) {
      if (key.startsWith('fin-flow:local-brief:')) throw new DOMException('quota', 'QuotaExceededError')
      return setItem.call(this, key, value)
    }
  })
  await page.goto('/en/workspace')
  const notebook = page.getByRole('region', { name: /^Browser notebook/ })
  await expect(notebook).toContainText('1 copies could not be read.')
  await page.getByLabel('Your perspective and questions').fill('Still editable despite quota failure')
  await notebook.getByRole('button', { name: 'Keep a copy of this draft' }).click()
  await expect(notebook.getByRole('alert')).toContainText('Browser storage could not be updated')
  await expect(page.getByLabel('Your perspective and questions')).toHaveValue('Still editable despite quota failure')
  await expect(notebook.getByRole('button', { name: /^Open saved draft/ })).toHaveCount(0)
  expect(await page.evaluate(() => localStorage.getItem('fin-flow:local-brief:v1:broken'))).toBe('{broken')
})

test('saved copies synchronize across tabs without overwriting unrelated copies or current work', async ({ page, context }) => {
  await page.goto('/en/workspace')
  const other = await context.newPage()
  await other.goto('/en/workspace')
  await page.getByLabel('Brief title').fill('From first tab')
  await other.getByLabel('Brief title').fill('From second tab')
  await page.getByRole('button', { name: 'Keep a copy of this draft' }).click()
  await other.getByRole('button', { name: 'Keep a copy of this draft' }).click()
  await expect(page.getByRole('button', { name: /^Open saved draft/ })).toHaveCount(2)
  await expect(other.getByRole('button', { name: /^Open saved draft/ })).toHaveCount(2)
  other.once('dialog', dialog => dialog.accept())
  await other.getByRole('button', { name: 'Delete saved draft From first tab' }).click()
  await expect(page.getByRole('button', { name: 'Open saved draft From first tab' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Open saved draft From second tab' })).toHaveCount(1)
  await expect(page.getByLabel('Brief title')).toHaveValue('From first tab')
  await other.close()
})

test('the Korean notebook is keyboard reachable and fits narrow screens', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 800 })
  await page.goto('/ko/workspace')
  await page.getByRole('button', { name: '브라우저 보관함 열기' }).click()
  await expect(page.getByRole('region', { name: /^브라우저 보관함/ })).toBeFocused()
  await page.getByLabel('브리핑 제목').fill('처음 알아본 금융 흐름')
  await page.getByRole('button', { name: '현재 초안 사본 보관' }).click()
  await expect(page.getByRole('button', { name: '보관본 열기 처음 알아본 금융 흐름' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
