import { test, expect } from '@playwright/test'

test('free briefing survives reload, compares networks and exports cited Markdown', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/en/workspace')
  await expect(page).toHaveTitle('Briefing workspace · Flow of Money')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('One clear briefing')
  await page.getByLabel('Brief title').fill('Payments onboarding')
  await page.getByLabel('Your perspective and questions').fill('Compare messaging with settlement.')
  await page.getByRole('checkbox', { name: 'Visa', exact: true }).check()
  await page.getByRole('checkbox', { name: 'Bond issuance', exact: true }).check()
  await expect(page.getByRole('checkbox', { name: 'Circle USDC', exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.getByLabel('Brief title')).toHaveValue('Payments onboarding')
  await expect(page.getByLabel('Your perspective and questions')).toHaveValue('Compare messaging with settlement.')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export Markdown', exact: true }).click()
  const file = await download
  expect(file.suggestedFilename()).toBe('Payments_onboarding.md')
  const stream = await file.createReadStream()
  let content = ''
  for await (const chunk of stream!) content += chunk.toString()
  expect(content).toContain('Compare messaging with settlement.')
  expect(content).toContain('Source review due')
  expect(content).toContain('https://')
  await expect(page.getByRole('button', { name: 'Explore Pro storage' })).toBeEnabled()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('plans preserve free entry and explain unavailable sales in both languages', async ({ page }) => {
  await page.goto('/ko/pricing?checkout=returned')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('금융 지식')
  await expect(page.getByRole('button', { name: '판매 준비 중' })).toBeDisabled()
  await page.getByRole('button', { name: 'Switch to English' }).click()
  await expect(page).toHaveURL(/\/en\/pricing\?checkout=returned/)
  await expect(page.getByRole('button', { name: 'Sales opening soon' })).toBeDisabled()
  await page.getByRole('button', { name: 'Create a free brief' }).click()
  await expect(page).toHaveURL(/\/en\/workspace$/)
  await expect(page.getByLabel('Brief title')).toBeVisible()
})

test('invalid stored draft and unavailable source data remain recoverable', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('fin-flow:brief-draft:v1', '{broken'))
  await page.route('**/data/sources.json', route => route.fulfill({ status: 503, body: 'unavailable' }))
  await page.goto('/en/workspace')
  await expect(page.getByLabel('Brief title')).toHaveValue('Financial flow comparison')
  await expect(page.getByRole('alert')).toContainText('Sources could not load')
  await expect(page.getByRole('button', { name: 'Export Markdown', exact: true })).toBeDisabled()
})


test('task templates protect existing work, support Escape and undo, and focus preview', async ({ page }) => {
  await page.goto('/en/workspace')
  await page.getByRole('button', { name: /^Compare issuance workflows/ }).click()
  await expect(page.getByLabel('Brief title')).toHaveValue('Compare issuance workflows')
  await page.getByLabel('Your perspective and questions').fill('My important research')
  await page.getByRole('button', { name: /^Prepare a lesson/ }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page.getByLabel('Your perspective and questions')).toHaveValue('My important research')
  await page.getByRole('button', { name: /^Prepare a lesson/ }).click()
  await page.getByRole('button', { name: 'Replace draft', exact: true }).click()
  await expect(page.getByLabel('Brief title')).toHaveValue('Prepare a lesson')
  await page.getByRole('button', { name: 'Undo draft replacement' }).click()
  await expect(page.getByLabel('Your perspective and questions')).toHaveValue('My important research')
  await page.getByRole('button', { name: 'View preview', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Brief preview', exact: true })).toBeFocused()
  await page.setViewportSize({ width: 320, height: 800 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('explorer handoff offers a network without overwriting the current draft', async ({ page }) => {
  await page.goto('/en/workspace')
  await page.getByLabel('Brief title').fill('Existing work')
  await page.goto('/en/map?network=etf-primary-market')
  await page.getByRole('button', { name: 'Create a brief with this network' }).click()
  await expect(page).toHaveURL(/workspace\?network=etf-primary-market/)
  await expect(page.getByLabel('Brief title')).toHaveValue('Existing work')
  await page.getByRole('button', { name: 'Add to draft', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: 'ETF primary market', exact: true })).toBeChecked()
  await expect(page).toHaveURL(/\/en\/workspace$/)
})

test('incomplete drafts survive reload and interface language does not translate the document', async ({ page }) => {
  await page.goto('/en/workspace')
  await page.getByLabel('Brief title').fill('')
  await page.getByRole('checkbox', { name: 'SWIFT', exact: true }).uncheck()
  await page.getByRole('checkbox', { name: 'CHIPS · Fedwire', exact: true }).uncheck()
  await page.getByLabel('Your perspective and questions').fill('Keep an incomplete thought')
  await page.reload()
  await expect(page.getByLabel('Brief title')).toHaveValue('')
  await expect(page.getByLabel('Your perspective and questions')).toHaveValue('Keep an incomplete thought')
  await expect(page.getByRole('button', { name: 'Export Markdown', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '한국어로 전환' }).click()
  await expect(page.getByLabel('문서 언어')).toHaveValue('en')
  await page.getByRole('button', { name: '요금제', exact: true }).click()
  await page.getByRole('button', { name: '작업실 열기', exact: true }).click()
  await expect(page.getByLabel('내 관점과 질문')).toHaveValue('Keep an incomplete thought')
})

test('source failures retry in place without losing work', async ({ page }) => {
  await page.route('**/data/sources.json', route => route.fulfill({ status: 503, body: 'unavailable' }))
  await page.goto('/en/workspace')
  await page.getByLabel('Brief title').fill('Retained on retry')
  await expect(page.getByRole('alert')).toContainText('Sources could not load')
  await page.unroute('**/data/sources.json')
  await page.getByRole('button', { name: 'Retry sources' }).click()
  await expect(page.getByRole('button', { name: 'Export Markdown', exact: true })).toBeEnabled()
  await expect(page.getByLabel('Brief title')).toHaveValue('Retained on retry')
})

test('blocked browser storage warns without disabling the editor', async ({ page }) => {
  await page.addInitScript(() => {
    const original = Storage.prototype.setItem
    Storage.prototype.setItem = function (key, value) {
      if (key.startsWith('fin-flow:')) throw new DOMException('blocked', 'SecurityError')
      return original.call(this, key, value)
    }
  })
  await page.goto('/en/workspace')
  await expect(page.getByRole('alert')).toContainText('Browser storage is blocked')
  await page.getByLabel('Brief title').fill('Editable without storage')
  await expect(page.getByLabel('Brief title')).toHaveValue('Editable without storage')
  await expect(page.getByRole('button', { name: 'Export Markdown', exact: true })).toBeEnabled()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('a four-network explorer handoff explains the limit and can be dismissed safely', async ({ page }) => {
  await page.goto('/en/workspace')
  await page.getByLabel('Brief title').fill('Full comparison')
  await page.getByRole('checkbox', { name: 'Visa', exact: true }).check()
  await page.getByRole('checkbox', { name: 'Bond issuance', exact: true }).check()
  await page.goto('/en/workspace?network=etf-primary-market')
  await expect(page.getByText('Remove one selected network to add this one.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Add to draft', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Dismiss', exact: true }).click()
  await expect(page).toHaveURL(/\/en\/workspace$/)
  await expect(page.getByLabel('Brief title')).toHaveValue('Full comparison')
  await expect(page.getByRole('checkbox', { name: 'ETF primary market', exact: true })).not.toBeChecked()
})
